In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('50_Startups.csv')
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [3]:
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

In [4]:
# input 
X=dataset.iloc[:,:-1].values
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [5]:
y=dataset.iloc[:,4].values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [7]:
le=LabelEncoder()

In [8]:
X[:,3]=le.fit_transform(X[:,3])

In [9]:
X

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [10]:
ohe=OneHotEncoder()

In [11]:
X=ohe.fit_transform(X).toarray()
X

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [12]:
# dummy variable trap ko remove or avoid krne ki koshish krenge
X=X[:,1:]

In [13]:
# train + test
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [15]:
X_train.shape

(40, 149)

In [16]:
X_test.shape

(10, 149)

In [17]:
y_train.shape

(40,)

In [18]:
# feature scaling 
from sklearn.preprocessing import StandardScaler

In [19]:
sc=StandardScaler()

In [20]:
X_train=sc.fit_transform(X_train)

In [21]:
X_train

array([[-0.16012815, -0.16012815, -0.16012815, ..., -0.81649658,
         1.73205081, -0.73379939],
       [-0.16012815, -0.16012815, -0.16012815, ..., -0.81649658,
        -0.57735027,  1.36277029],
       [-0.16012815, -0.16012815, -0.16012815, ..., -0.81649658,
         1.73205081, -0.73379939],
       ...,
       [-0.16012815, -0.16012815, -0.16012815, ..., -0.81649658,
        -0.57735027,  1.36277029],
       [-0.16012815, -0.16012815, -0.16012815, ...,  1.22474487,
        -0.57735027, -0.73379939],
       [-0.16012815, -0.16012815, -0.16012815, ...,  1.22474487,
        -0.57735027, -0.73379939]])

In [22]:
X_test=sc.fit_transform(X_test)

In [23]:
X_test

array([[ 0.        ,  0.        ,  0.        , ..., -0.33333333,
         0.81649658, -0.65465367],
       [ 0.        ,  0.        ,  0.        , ...,  3.        ,
        -1.22474487, -0.65465367],
       [ 0.        ,  0.        ,  0.        , ..., -0.33333333,
         0.81649658, -0.65465367],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -0.33333333,
        -1.22474487,  1.52752523],
       [ 0.        ,  0.        ,  0.        , ..., -0.33333333,
         0.81649658, -0.65465367],
       [ 0.        ,  0.        ,  0.        , ..., -0.33333333,
         0.81649658, -0.65465367]])

In [24]:
# model creation
from sklearn.linear_model import LinearRegression

In [25]:
lr=LinearRegression()

In [26]:
# train
lr.fit(X_train,y_train)

LinearRegression()

In [27]:
y_pred=lr.predict(X_test)

In [28]:
y_pred

array([110061.12547932, 101486.04466051, 108958.95767548, 109216.86651088,
       109529.33042719, 111594.56837348, 111693.08130932, 113240.72648136,
       109154.44115526, 109529.33042719])

In [29]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [30]:
lr.score(y_test , y_pred)

ValueError: Expected 2D array, got 1D array instead:
array=[103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
print("MSE :",mean_squared_error(y_test,y_pred))

In [ ]:
x=dataset.iloc[:,0]
y1=dataset.iloc[:,4]         

In [ ]:
plt.plot(x,y1,'rx')
plt.plot(x,y1,c='black')